### ISSUE TITLE
Running a non elixir task?

### ISSUE THREAD

**Issue by mme** [seated/faktory_worker#112]
How do I run ```perform_async()``` for a task written in another language, e.g. python?

**Comment by swelham** [comment]
You should be able to do this is by sending the job to a queue the python client is pulling from.

Do you have an example of how you're trying this?

**Comment by mme** [comment]
@swelham thanks for the reply! In my concrete example I'm trying to trigger an NLP python job on another server, but for simplicity let's assume I want to call this python function registered as "adder" (https://www.mikeperham.com/2019/01/08/using-faktory-with-python/):

```python
def adder(x, y):
    logging.info("%d + %d = %d", x, y, x + y)

w = Worker(queues=['default'], concurrency=1)
w.register('adder', adder)
w.run()
```

BTW here is how the ruby lib handles this: https://github.com/contribsys/faktory/issues/259

**Comment by swelham** [comment]
Thanks for the clear example 🙂 

I believe all we're missing here is the ability to override the `jobtype` sent to Faktory. I have opened a PR (#113) that fixes this and should solve your problem.

Once that's merged I will push up a new release.

**Comment by mme** [comment]
Great, thanks a lot!
